services:
  leaderboard:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
    depends_on:
      - leaderboarddata

  leaderboarddata:
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: LeaderboardDB
      PGPORT: "5432"
    ports:
      - "5432"
    volumes:
      - ./database:/var/lib/postgresql/data/

  pgadmin:
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: alper@askin.com
      PGADMIN_DEFAULT_PASSWORD: alper
    ports:
      - "81:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin

  redis:
    restart: always
    image: "redis:alpine"    
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data




